name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: deps
      run: sudo apt-get install libftdi1-dev
    - uses: actions/checkout@v2
    - name: bootstrap
      run: autoreconf -vfi
    - name: configure
      run: ./configure
    - name: make distcheck
      run: make distcheck
